const Ziggy = {
    url: 'http:\/\/localhost',
    port: null,
    defaults: {},
    routes: {
        'sanctum.csrf-cookie': { uri: 'sanctum\/csrf-cookie', methods: ['GET', 'HEAD'] },
        'admin.scheduling.capacities.index': { uri: 'admin\/scheduling\/capacidades', methods: ['GET', 'HEAD'] },
        'admin.scheduling.capacities.store': { uri: 'admin\/scheduling\/capacidades', methods: ['POST'] },
        'cliente.dashboard': { uri: 'cliente\/dashboard', methods: ['GET', 'HEAD'] },
        dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'] },
        'profile.edit': { uri: 'profile', methods: ['GET', 'HEAD'] },
        'profile.update': { uri: 'profile', methods: ['PATCH'] },
        'profile.destroy': { uri: 'profile', methods: ['DELETE'] },
        register: { uri: 'register', methods: ['GET', 'HEAD'] },
        login: { uri: 'login', methods: ['GET', 'HEAD'] },
        'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
        'password.email': { uri: 'forgot-password', methods: ['POST'] },
        'password.reset': { uri: 'reset-password\/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'password.store': { uri: 'reset-password', methods: ['POST'] },
        'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
        'verification.verify': {
            uri: 'verify-email\/{id}\/{hash}',
            methods: ['GET', 'HEAD'],
            parameters: ['id', 'hash'],
        },
        'verification.send': { uri: 'email\/verification-notification', methods: ['POST'] },
        'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
        'password.update': { uri: 'password', methods: ['PUT'] },
        logout: { uri: 'logout', methods: ['POST'] },
        'clientes.index': { uri: 'clientes', methods: ['GET', 'HEAD'] },
        'clientes.create': { uri: 'clientes\/crear', methods: ['GET', 'HEAD'] },
        'clientes.store': { uri: 'clientes', methods: ['POST'] },
        'clientes.show': {
            uri: 'clientes\/{cliente}',
            methods: ['GET', 'HEAD'],
            parameters: ['cliente'],
            bindings: { cliente: 'id' },
        },
        'clientes.edit': {
            uri: 'clientes\/{cliente}\/editar',
            methods: ['GET', 'HEAD'],
            parameters: ['cliente'],
            bindings: { cliente: 'id' },
        },
        'clientes.update': {
            uri: 'clientes\/{cliente}',
            methods: ['PATCH'],
            parameters: ['cliente'],
            bindings: { cliente: 'id' },
        },
        'clientes.destroy': {
            uri: 'clientes\/{cliente}',
            methods: ['DELETE'],
            parameters: ['cliente'],
            bindings: { cliente: 'id' },
        },
        'clientes.vehiculos.create': {
            uri: 'clientes\/{cliente}\/vehiculos\/crear',
            methods: ['GET', 'HEAD'],
            parameters: ['cliente'],
            bindings: { cliente: 'id' },
        },
        'clientes.vehiculos.store': {
            uri: 'clientes\/{cliente}\/vehiculos',
            methods: ['POST'],
            parameters: ['cliente'],
            bindings: { cliente: 'id' },
        },
        'clientes.vehiculos.edit': {
            uri: 'clientes\/{cliente}\/vehiculos\/{vehiculo}\/editar',
            methods: ['GET', 'HEAD'],
            parameters: ['cliente', 'vehiculo'],
            bindings: { cliente: 'id', vehiculo: 'id' },
        },
        'clientes.vehiculos.update': {
            uri: 'clientes\/{cliente}\/vehiculos\/{vehiculo}',
            methods: ['PATCH'],
            parameters: ['cliente', 'vehiculo'],
            bindings: { cliente: 'id', vehiculo: 'id' },
        },
        'clientes.vehiculos.destroy': {
            uri: 'clientes\/{cliente}\/vehiculos\/{vehiculo}',
            methods: ['DELETE'],
            parameters: ['cliente', 'vehiculo'],
            bindings: { cliente: 'id', vehiculo: 'id' },
        },
        'inventario.products.index': { uri: 'inventario\/productos', methods: ['GET', 'HEAD'] },
        'inventario.products.create': { uri: 'inventario\/productos\/crear', methods: ['GET', 'HEAD'] },
        'inventario.products.store': { uri: 'inventario\/productos', methods: ['POST'] },
        'inventario.products.edit': {
            uri: 'inventario\/productos\/{product}\/editar',
            methods: ['GET', 'HEAD'],
            parameters: ['product'],
            bindings: { product: 'id' },
        },
        'inventario.products.update': {
            uri: 'inventario\/productos\/{product}',
            methods: ['PATCH'],
            parameters: ['product'],
            bindings: { product: 'id' },
        },
        'inventario.products.destroy': {
            uri: 'inventario\/productos\/{product}',
            methods: ['DELETE'],
            parameters: ['product'],
            bindings: { product: 'id' },
        },
        'inventario.suppliers.index': { uri: 'inventario\/proveedores', methods: ['GET', 'HEAD'] },
        'inventario.suppliers.create': { uri: 'inventario\/proveedores\/crear', methods: ['GET', 'HEAD'] },
        'inventario.suppliers.store': { uri: 'inventario\/proveedores', methods: ['POST'] },
        'inventario.suppliers.edit': {
            uri: 'inventario\/proveedores\/{supplier}\/editar',
            methods: ['GET', 'HEAD'],
            parameters: ['supplier'],
            bindings: { supplier: 'id' },
        },
        'inventario.suppliers.update': {
            uri: 'inventario\/proveedores\/{supplier}',
            methods: ['PATCH'],
            parameters: ['supplier'],
            bindings: { supplier: 'id' },
        },
        'inventario.suppliers.destroy': {
            uri: 'inventario\/proveedores\/{supplier}',
            methods: ['DELETE'],
            parameters: ['supplier'],
            bindings: { supplier: 'id' },
        },
        'mecanico.dashboard': { uri: 'mecanico\/dashboard', methods: ['GET', 'HEAD'] },
        'work-orders.index': { uri: 'ordenes-trabajo', methods: ['GET', 'HEAD'] },
        'work-orders.create': {
            uri: 'ordenes-trabajo\/crear\/vehiculo\/{vehiculo}',
            methods: ['GET', 'HEAD'],
            parameters: ['vehiculo'],
            bindings: { vehiculo: 'id' },
        },
        'work-orders.store': { uri: 'ordenes-trabajo', methods: ['POST'] },
        'work-orders.show': {
            uri: 'ordenes-trabajo\/{workOrder}',
            methods: ['GET', 'HEAD'],
            parameters: ['workOrder'],
            bindings: { workOrder: 'id' },
        },
        'work-orders.update': {
            uri: 'ordenes-trabajo\/{workOrder}',
            methods: ['PATCH'],
            parameters: ['workOrder'],
            bindings: { workOrder: 'id' },
        },
        'work-orders.destroy': {
            uri: 'ordenes-trabajo\/{workOrder}',
            methods: ['DELETE'],
            parameters: ['workOrder'],
            bindings: { workOrder: 'id' },
        },
        'work-orders.products.add': {
            uri: 'ordenes-trabajo\/{workOrder}\/products',
            methods: ['POST'],
            parameters: ['workOrder'],
            bindings: { workOrder: 'id' },
        },
        'work-orders.products.remove': {
            uri: 'ordenes-trabajo\/{workOrder}\/products\/{product}',
            methods: ['DELETE'],
            parameters: ['workOrder', 'product'],
            bindings: { workOrder: 'id', product: 'id' },
        },
        'work-orders.services.add': {
            uri: 'ordenes-trabajo\/{workOrder}\/services',
            methods: ['POST'],
            parameters: ['workOrder'],
            bindings: { workOrder: 'id' },
        },
        'work-orders.services.remove': {
            uri: 'ordenes-trabajo\/{workOrder}\/services\/{service}',
            methods: ['DELETE'],
            parameters: ['workOrder', 'service'],
            bindings: { workOrder: 'id', service: 'id' },
        },
        'work-orders.external-costs.add': {
            uri: 'ordenes-trabajo\/{workOrder}\/external-costs',
            methods: ['POST'],
            parameters: ['workOrder'],
            bindings: { workOrder: 'id' },
        },
        'work-orders.external-costs.remove': {
            uri: 'ordenes-trabajo\/external-costs\/{externalCost}',
            methods: ['DELETE'],
            parameters: ['externalCost'],
            bindings: { externalCost: 'id' },
        },
        'work-orders.assign-mechanic': {
            uri: 'ordenes-trabajo\/{workOrder}\/assign-mechanic',
            methods: ['PATCH'],
            parameters: ['workOrder'],
            bindings: { workOrder: 'id' },
        },
        'storage.local': {
            uri: 'storage\/{path}',
            methods: ['GET', 'HEAD'],
            wheres: { path: '.*' },
            parameters: ['path'],
        },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
